user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    types_hash_max_size 4096;
    charset utf-8;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    server {
        listen 80;
        listen 8080;
        listen [::]:80;
        listen [::]:8080;
        server_name _;
        root /var/www/wow-spec-cards;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(jpg|jpeg|png|gif|webp|mp4|webm|css|js)$ {
            expires 7d;
            add_header Cache-Control "public";
            try_files $uri =404;
        }
    }
}
